import React, { useState, useEffect } from 'react';
import { collection, addDoc, updateDoc, doc, onSnapshot, query, orderBy } from 'firebase/firestore';
import { db } from './firebase';
import Sidebar from './components/Sidebar';
import Dashboard from './components/Dashboard';
import TransactionForm from './components/TransactionForm';
import InventoryList from './components/InventoryList';
import Reports from './components/Reports';
import { Transaction, StockItem } from './types';

const App: React.FC = () => {
  const [currentView, setCurrentView] = useState('dashboard');
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [loading, setLoading] = useState(true);

  // Calculate stock based on transactions
  const [stock, setStock] = useState<StockItem[]>([]);
  const [inventoryMap, setInventoryMap] = useState<Record<string, number>>({});

  // 1. Load Data from Firebase in Real-Time
  useEffect(() => {
    const q = query(collection(db, "transactions"), orderBy("timestamp", "desc"));
    
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const loadedTransactions = snapshot.docs.map(doc => ({
        ...doc.data(),
        id: doc.id // Use Firestore ID as the source of truth
      })) as Transaction[];
      
      setTransactions(loadedTransactions);
      setLoading(false);
    }, (error) => {
      console.error("Error fetching transactions:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  // 2. Derive Stock from Transactions
  useEffect(() => {
    // Logic to derive stock from transaction history
    const stockMap: Record<string, StockItem> = {};
    const simpleMap: Record<string, number> = {};

    // Sort by date old to new to replay history correctly
    // We reverse the state because we store them Descending (Newest first) in state for UI
    const sortedForCalculation = [...transactions].sort((a, b) => a.timestamp - b.timestamp);

    sortedForCalculation.forEach(t => {
      // Key defines a unique stock bucket: Material + Subtype + Lot
      const key = `${t.material}-${t.subtype || 'NA'}-${t.lot}`;
      
      if (!stockMap[key]) {
        stockMap[key] = {
          id: key,
          material: t.material,
          subtype: t.subtype,
          lot: t.lot,
          quantity: 0,
          lastUpdated: t.date
        };
      }

      if (t.type === 'IN') {
        stockMap[key].quantity += t.quantity;
      } else {
        stockMap[key].quantity -= t.quantity;
      }
      stockMap[key].lastUpdated = t.date;
    });

    // Filter valid stock
    const stockArray = Object.values(stockMap).filter(item => item.quantity > 0);
    
    // Create simple map for quick lookup during validation
    stockArray.forEach(item => {
      simpleMap[item.id] = item.quantity;
    });

    setStock(stockArray);
    setInventoryMap(simpleMap);

  }, [transactions]);

  // Save new transaction to Firebase
  const handleSaveTransaction = async (t: Transaction) => {
    try {
      // Create a clean object without the temporary ID generated by the form, 
      // Firestore will assign a new ID.
      const { id, ...transactionData } = t;
      await addDoc(collection(db, "transactions"), transactionData);
    } catch (e) {
      console.error("Error adding document: ", e);
      alert("Error al guardar en la base de datos.");
    }
  };

  // Update existing transaction in Firebase
  const handleUpdateTransaction = async (updatedT: Transaction) => {
    try {
      const transactionRef = doc(db, "transactions", updatedT.id);
      // We only send the fields, Firestore handles the rest
      const { id, ...dataToUpdate } = updatedT;
      await updateDoc(transactionRef, dataToUpdate);
    } catch (e) {
      console.error("Error updating document: ", e);
      alert("Error al actualizar el registro.");
    }
  };

  const renderContent = () => {
    if (loading) {
      return (
        <div className="flex items-center justify-center h-full">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-medical-600"></div>
        </div>
      );
    }

    switch (currentView) {
      case 'dashboard':
        return <Dashboard stock={stock} transactions={transactions} />;
      case 'entry':
        return <TransactionForm type="IN" onSave={handleSaveTransaction} inventoryMap={inventoryMap} />;
      case 'exit':
        return <TransactionForm type="OUT" onSave={handleSaveTransaction} inventoryMap={inventoryMap} />;
      case 'inventory':
        return <InventoryList stock={stock} />;
      case 'reports':
        return <Reports transactions={transactions} onUpdateTransaction={handleUpdateTransaction} />;
      default:
        return <Dashboard stock={stock} transactions={transactions} />;
    }
  };

  return (
    <div className="flex h-screen bg-slate-50 font-sans text-slate-900">
      <Sidebar currentView={currentView} setView={setCurrentView} />
      <main className="flex-1 flex flex-col min-w-0 overflow-hidden">
        {/* Header */}
        <header className="bg-white border-b border-slate-200 px-8 py-4 flex justify-between items-center shadow-sm z-10">
          <h2 className="text-xl font-bold text-slate-800 capitalize">
            {currentView === 'entry' ? 'Ingreso de Material' : 
             currentView === 'exit' ? 'Salida de Material' : 
             currentView === 'inventory' ? 'Inventario General' : 
             currentView}
          </h2>
          <div className="flex items-center gap-4">
             <div className="text-right hidden md:block">
                <p className="text-sm font-bold text-slate-800">Admin Usuario</p>
                <p className="text-xs text-slate-500">Medicina Preventiva</p>
             </div>
             <div className="h-10 w-10 bg-medical-100 rounded-full flex items-center justify-center text-medical-700 font-bold">
                MP
             </div>
          </div>
        </header>

        {/* Scrollable Content Area */}
        <div className="flex-1 overflow-auto p-8">
          <div className="max-w-7xl mx-auto">
            {renderContent()}
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;